function skillsMember() {
  var skills = [
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Node.js",
    "Express",
    "MongoDB",
    "Python",
    "Java",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "Kotlin",
    "Dart",
    "Flutter",
    "Vue.js",
    "Angular",
    "SQL",
    "PostgreSQL",
    "SQLite",
    "Firebase",
    "AWS",
    "Azure",
    "GCP",
    "Heroku",
    "Netlify",
    "Vercel",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Jira",
    "Confluence",
    "Trello",
    "Slack",
    "Discord",
    "Zoom",
    "Microsoft Teams",
    "Google Meet",
    "Figma",
    "Sketch",
    "Adobe XD",
    "InVision",
    "Zeplin",
    "GraphQL",
    "REST API",
    "CI/CD",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Travis CI",
    "CircleCI",
    "GitHub Actions",
    "GitLab CI",
    "Jest",
    "Mocha",
    "Chai",
    "Cypress",
    "Selenium",
    "Puppeteer",
    "Jupyter",
    "VSCode",
    "Sublime Text",
    "Atom",
    "WebStorm",
    "PyCharm",
    "IntelliJ IDEA",
    "Eclipse",
    "Visual Studio",
    "Xcode",
    "Android Studio",
    "Unity",
    "Unreal Engine",
    "Blender",
    "Maya",
    "Photoshop",
    "Illustrator",
    "Premiere Pro",
    "After Effects",
    "Final Cut Pro",
    "Logic Pro",
    "Pro Tools",
    "Ableton Live",
    "FL Studio",
    "SketchUp",
    "AutoCAD",
    "SolidWorks",
    "Raspberry Pi",
    "Arduino",
    "ESP32",
    "IoT",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Big Data",
    "Data Science",
    "Data Analytics",
    "Data Engineering",
  ];
  return skills;
}